<?php
    require_once('config.php');
    $level=L0;
    $_isHome=false;
    $_isHome02=true;
    $_isHome03=false;
    $_isAbout=false;
    $_isBlogDetail=false;
    $_isBlog=false;
    $_isContact=false;
    $_isProdDetail=false;
    $_isProduct=false;
	$_isShop=false;
    require_once($level.'layout.php')
?>